language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
branches:
  only:
  - master
  - devel
# Latest node
before_install:
  - nvm install 8.3.0
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
  - export PATH=$HOME/.yarn/bin:$PATH
# Install dependencies
install:
  - yarn install
  - yarn build
  - yarn copy
  - cd py
  - pip install --upgrade pip==18.0 setuptools wheel
  - pip install swiglpk --only-binary swiglpk
  - pip install -e .
  - cd ..
# Run tests
script:
  - yarn test
#  - if [[ $TRAVIS_PYTHON_VERSION = '3.6' ]]; then yarn coverage; fi
  - cd py
  - python setup.py test
  - cd ..
  - npm run build
# No emails
notifications:
  email: false
  slack:
    rooms:
      - secure: "UONml9kjcaQBV5uMwTm6LE/G0j2ZCsQw2IbvvBz/lBOL7tz/mF2gDCWcSt+5/ZXhGvsAa8vlWJkN9Gfo4LUPTl3CPA0Nrx/30BxGS+2iVCawC0x00jNEgzoEjHV0CEUziFXemJPbE7wDlNgekTU9EvNMAUhlTr5AbTiNxYhTINCLp2hbhd1UIcy6GatagllBOl0sPZHxJBQlVQwhnoLvIfaCqEEolSnqoqoD52GXcSayctr0N5yPOno5eNEMS7J44cNVOWYBQksqggKpF1y3w07yv96iMKSbnCXynTDaBx4iMGTs2TJWaxbxubtZIRDgT+7YdNbpuTNh3cB1fA5hHAxgaDbEy0BqiKZUx7Gbr8B9Fq14z/zHF6VSQDmUkbMB7mgUqLEX5B2NMLKg58M3N1W1ynQbtLE6+kidgVzrU2yCAAysi58suA6TV+C1KvJxoD78U96IeORsEQExEBGwU0RCKLe+Qd4J3xlgQWOLRTygdQ+KTwSHrijOoGGvWxi9EldVn1QqV1yn1Z7UOxeRSh7fAZ6YovEgN41rPnNLIXE4G89Dx7SBWmo9BINmZa5B6JIFnjztRiszAku1wBS24G6uI6IO3IzIlHU01eKk0jVXa+7g9PUVjmN1ICoUPs6iYNcwSgo2wVW6Mn7l/S6kTceS4BAetHNxI8twcFtC45U="
    on_success: change
    on_failure: change
    on_pull_requests: false
# Run with containers
sudo: false
deploy:
  provider: npm
  email: ali@kvikshaug.no
  api_key:
    secure: "zPUUD/DJiPXywT+98bGDhAHr4V00a6FcYcsZKoL5KKgNXTS62aXJq+gB0MpnHu1qmorzH4NQEFnjvVmCKzGVvFUvUxsKKsDWWjq39pnTMXdOVzHsr22Az6jrz5VAAicRFKM0LZ5Byq7wxcqcwqhGxUdN05kYcfrnQ5gm83UHPsTQwNLhK136vGngOTI37vLfVEl8KrR0B7yobD5XK1SWl6VHWQlOjwMPbCbKDTYXh3A/UkO6cA3yipBMZwshpQijrSvq7Fb2HQVH1J7TxUONegqxPP+a7lM1KnI7VJrEEWjF4z2oHWg0uBm83cjWUrLG+TOoM/Dn90MMCxjDYJ5w2RuWjj1AqFqX6P5dvEIGMgm8mWg7DbyBcp6dAhLm15+o1nsqBHf0Tn6+Mu3m2hD+o75hWy22Fb73Ehw9vd+GGNGcelzjmHuIfcrt7R4N+Ipq+vEVan0jY34rKX9hY+fU2AAp+065uoSDCVZEIg2TDX/TCd8WUFOE0VhYXqIZNpJv7hniweb9h5/DE30Q4y8JQjan8HwmQF48BD/1oIdaL6MP9ukVDiQPmUCJ4Bf4kZipdUgozLiH6kAo+mUHFqwqqmkwnJ1/+rqj64Y46GyxNgXDvyjWkyHgVK085A1wG1UD+FOvrl8gFPYMduUp/yQ2F2ad9A6zSuec0+Hl4+XlrB4="
  on:
    tags: true
    repo: DD-DeCaF/escher
  skip_cleanup: true
