environment:
  matrix:
    - python: 'C:\\Python36-x64'
      nodejs_version: '11'

    - python: 'C:\\Python37-x64'
      nodejs_version: '11'

install:
  # Add python to PATH
  - 'SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%'
  - python --version
  # Set node version
  - ps: 'Install-Product node $env:NODEJS_VERSION'
  - node --version
  # Install js packages
  - yarn install
  - yarn build
  - yarn copy
  # Install python packages
  - python -m pip install --upgrade pip
  - cd py
  - python -m pip install -e .
  - cd ..

build: off

test_script:
  - yarn test
  - cd py
  - python -m pytest
  - cd ..

artifacts:
  - path: py\dist\*
